let express=require("express")
const { ureg, userlog, userdet, updmarks } = require("../controllers/usercon")
const { Areg, adminlog } = require("../controllers/admincon")
const { qns, getqns } = require("../controllers/qncon")
let route=new express.Router()
route.post("/adreg",Areg)
route.post("/usreg",ureg)
route.post("/userlogin",userlog)
route.post("/adminlogin",adminlog)
route.post("/addqsn",qns)
route.get("/getqns",getqns)
route.get("/userdet/:id",userdet)
route.put("/updmarks",updmarks)
module.exports=route